server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
      - id : user.cmd.api-registerUser
        uri : http://localhost:8081/api/v1/registerUser
        predicates:
          - Path=/api/v1/registerUser
      - id : user.cmd.api-updateUser
        uri : http://localhost:8081/api/v1/updateUser/**
        predicates:
          - Path=/api/v1/updateUser/**
      - id : user.cmd.api-removeUser
        uri : http://localhost:8081/api/v1/removeUser/**
        predicates:
          - Path=/api/v1/removeUser/**
          
      - id : user.query.api
        uri : http://localhost:8082/api/v1/userLookup/**
        predicates:
          - Path=/api/v1/userLookup/**